### ISSUE TITLE
Errors in Make

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/spartan-refactoring#104]

**Comment by dormaayan** [comment]
`Description	Resource	Path	Location	Type
Make cannot be resolved	MakeAST.java	‪/il.org.spartan.refactoring/src/main/java/il/org/spartan/refactoring/utils‬	line 25	Java Problem
`

**Comment by yossigil** [comment]
I this still open? i got a clean test.

**Comment by dormaayan** [comment]
Solved Temporarily

**Comment by yossigil** [comment]
Good job, @dormaayan
