### ISSUE TITLE
Employ overloading to determine a subset of prudent type

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#105]
@NivShalmon : We will need a service for testing, that would give the real type of an expression whose type is unknown to us, because we did not study every bit of the language semantics.

Typical use would be 
```java
@Test public void makeSureIUnderstandSemanticsOfShift() {
azzert.that(PrudentType.axiom(((short)1)<<1L)),is(PrudentType.INT))
}
```
Function `axiom(e)` tells you the compile time type of an expression. It just returns one out of the _**self certain**_ values of `PrudentType`, e.g., 

- `PrudentType.INT`
- `PrudentType.CHAR`
- `PrudentType.SHORT`

but not `PrudentType.ALPHANUMERIC`. 

Function `axiom` is lot of fun, since it does not really examine the type. It counts on overloading
for doing it. It cheats, by letting  the compiler overloading management to dispatch to different
versions of the 10 or so of `axiom`.

This might be very confusing, but  you can see an example here

https://github.com/SpartanRefactoring/spartan-refactoring/blob/master/src/main/java/il/org/spartan/refactoring/java/atomic.java

You won't understand much of this before you check the class of testing this one.
Do use Ctrl+SHIFT+G in Eclipse.

**Comment by NivShalmon** [comment]
I commited axiom as well as the test you wrote about. Will write some more tests using it soon.

**Comment by yossigil** [comment]
Very good job. Try to spartanize your own code with the market place plugin.

**Comment by yossigil** [comment]
Good job. I am closing this issue
