### ISSUE TITLE
Wring: Convert x=x#y to x#=y

### ISSUE THREAD

**Issue by dngreenst** [SpartanRefactoring/spartan-refactoring#108]
Same as Issue 103

**Comment by yossigil** [comment]
Does it use the wizard?

**Comment by yossigil** [comment]
Was this also done for other operators? Which?

**Comment by dngreenst** [comment]
Only for multiplication. Seemed like a shame not to do it, the wrings are almost identical.

**Comment by yossigil** [comment]
So, the  work in `wring` was not used/

**Comment by sakopzon** [comment]
Dan added the wizard use instead of the string comparison I wrote, and it works just fine!
Which work in wring do you mean?

**Comment by yossigil** [comment]
Here is the question: can you do a = a # b => a #= b for all operators #. If no, pleas finish BEFORE the environment. Both of you absolutely need the drill!  If Yes, please place a link that demonstrates.

**Comment by sakopzon** [comment]
Got you, wizard has all we need

**Comment by sakopzon** [comment]
Unresolved issues after enhancement:
-The trimmer doesn't recognize XOR operator "^".
-The wizard diagnoses left/right shift operators as associative.

**Comment by yossigil** [comment]
So, fix them! Make sure to preserve as much of the semantics as you can. Be smart.

Are they, or aren't they?

**Comment by dngreenst** [comment]
For reasons unknown, 
"x=x^y" and "x^=y"
are not compiled by the trimmer
but "x = x ^ y" and "x ^= y" 
pose no problem.

**Comment by yossigil** [comment]
We do not leave "reason unknown"

**Comment by dngreenst** [comment]
Issue #115 opened regarding XOR bug.
