### ISSUE TITLE
Concat StringLiterals

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/spartan-refactoring#120]
Concat StringLiterals when we can, for example:
`"a "+"string"`-->`"a string"`

This will be very usefull for issue #110

**Comment by yossigil** [comment]
Wouldn't this break all of our tests?

**Comment by NivShalmon** [comment]
All tests pass at the moment, and this is already implemented and in the toolbox. It might try to spartanize tests we don't want when using the plugin on the tests

**Comment by yossigil** [comment]
I mean that if you run the plugin on the project itself, it will ruin the layout of our `@Test` methods which use a lot of string made by adding   of literals

**Comment by NivShalmon** [comment]
It might. This turned out to be unnececary to issue #110 as well, so we can just remove this if you want

**Comment by yossigil** [comment]
Shame to remove it. Just disable it from the trimmer for now.

**Comment by NivShalmon** [comment]
Alright, this is commented in the toolbox for now, can be edited back whenever we want to. The tests for this are ignored as well

**Comment by dormaayan** [comment]
@yossigil :

What do you mean by infinite loop ? we ran the plugin on the project and it worked the same with and without the CleverTrenarization.

**Comment by yossigil** [comment]
I mean that the build gets stuck. It cannot build itself.

**Comment by dormaayan** [comment]
@yossigil :
@NivShalmon  and me ran the plugin with the code and ran the tests from the plugin, we don't see the problem you are talking about, and the spartanization mechanism works as well.

**Comment by NivShalmon** [comment]
This issue is already finished, currently the code exists but isn't in the toolbox, and @yossigil said the issue with the plugin is solved too, so I'm closing this issue
