### ISSUE TITLE
Rethink limiting the number of chained ternary operators

### ISSUE THREAD

**Issue by mittelman** [SpartanRefactoring/spartan-refactoring#19]
We discussed this in the past, however nothing was done.

Nowadays, the plugin converts an if statement with multiples cases into a very long ternary chain, for example:

```java
if(exp1)
    stmt1;
else if(exp2)
    stmt2;
else if(exp3)
    stmt3;
else
    stmt4;
```

Becomes:

```java
exp1 ? stmt1 : exp2 ? stmt2 : exp3 ? stmt3 : stmt4;
```

I believe this isn't readable and makes understanding the code much harder. I believe we should limit this to at most 2 chained if-else statements (`exp1 ? stmt1 : exp2 ? stmt2 : stmt3`)

**Comment by yossigil** [comment]
Will not do.
