### ISSUE TITLE
Wring: Reorder comparison with string literals

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#21]
Convert a.equals("a") to "a".equals(a);
Also, for equalsIgnoreCase

**Comment by OriRoth** [comment]
@mittelman Is there a wring to do that? You said it is an old issue and it appears in TrimmerTest... anyway I am writing it again

**Comment by yossigil** [comment]
I thought there was a wring but I lost track of it

**Comment by OriRoth** [comment]
See wring StringEqualsConstant - no bindings were used (should it? probably not)
