### ISSUE TITLE
Wring: Change unused variable name to __

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#23]
In all cases that a variable is annotated with @suppersswarnings("Unused")
change, if possible variable name to __ (double underscore).

This applies to parameters
local variables,
but not fields.

Do NOT invoke eclipse rename.

**Comment by yossigil** [comment]
This should be a spartanization.

**Comment by OriRoth** [comment]
Is there a something to be done in case of multiple unused variables, or are we going to ignore this case?

**Comment by OriRoth** [comment]
See wring MethodRenameUnusedVariableToUnderscore. Changes unused variable name, annotated with @SuppressWarnings("unused") or @SuppressWarnings( { ... "unused" ... } ), into double underscore "__". Deals with many unused variables by renaming the first one (and only it!).

**Comment by OriRoth** [comment]
Should we change the parent class of this wring to VariableChangeName (parent class for changing variables names)? It is better designed *but* has a much bigger complexity, and clearly has a great potential for slowing the spartanization process of large projects.

**Comment by yossigil** [comment]
I would say no. Leave it as is.
