### ISSUE TITLE
Wring: Change all variable names from _ to __

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#24]
Add spartanization to this effect

**Comment by yossigil** [comment]
Good job with the multiple-distributed wring concept!

**Comment by OriRoth** [comment]
See wring VariableRenameUnderscoreToDoubleUnderscore. In order to implement this wring, I have created a parent wring VariableChangeName that suppose to deal with all variables/parameters renamings. Use example:
<pre><code>
class A {
	int /*com1*/_;
	int f(int _) {
		return /**com2*/_;
	}
}
</code></pre>
==>
<pre><code>
class A {
	int /*com1*/__;
	int f(int __) {
		return /**com2*/__;
	}
}
</code></pre>

**Comment by yossigil** [comment]
Install and fix the code.
