### ISSUE TITLE
spartanization: x.size() == 0 ===> x.isEmpty()

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#28]
also
x.size() != 0 ===> !x.isEmpty()

Note: this requires binding information

**Comment by OriRoth** [comment]
See new Wring CollectionZeroSize. Also added BindingUtils to utils. Takes care of:
x.size() != 0 ===> !x.isEmpty()
x.size() > 0 ===> !x.isEmpty()
x.size() == 0 ===> x.isEmpty()
if x.isEmpty() method accepts no parameters and returns boolean/Boolean.
Currently I do not know how to get *accessible* methods using binding - this wring works only for x with a *public* size method.

**Comment by yossigil** [comment]
What does this "Currently I do not know how to get accessible methods using binding" mean?

**Comment by OriRoth** [comment]
One can call x.isEmpty() when the method is public, but also when:
1) the method is private, and we are in x class context.
2) the method is protected, and we are in a context of a class with x class as an ancestor.
3) (more? less?)
I guess getting an accessible method (by regarding context) is very useful - if I would not find any existing solution I will try write it myself and add it to the wring (and utils).

**Comment by yossigil** [comment]
Got it. Thanks.

Do not worry about this. In the rare cases in which visibility makes a problem, the programmer may still want to do the spartanization, and then change the visibility.

**Comment by mittelman** [comment]
In my opinion, this wring should be applied to Collections only. Need to check whether the type actually implements Collection
