### ISSUE TITLE
Many wrings: to Deal with switch

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#30]
E.g.,

switch (x) {
asdfasdf:
break;
}
return
to 
switch (x) {
asdfasdf:
return;
}

**Comment by OriRoth** [comment]
See Wring SwitchBreakReturn. In order to implement this wring, I have created a new Wring subclass MultipleReplaceToNextStatement. This type of Wring replaces multiple nodes (or a single node) in current statement with multiple nodes (or a single node) in next statement. The logic making it happen is placed in MultipleReplaceToNextStatement, so the wring (SwitchBreakReturn) itself is very simple (check for yourself!).
Example (with comments):
switch (x) {
		case 1:
			System.out.println("1 detected");
			break; // com1
		case 2:
			System.out.println("2 detected"); // com2
			break;
		default:
			System.out.println("wrong number!");
			return "failue";
		}
		return "success"; // com3
===>
switch (x) {
		case 1:
			System.out.println("1 detected");
			// com1
			// com3
			return "success";
		case 2:
			System.out.println("2 detected"); // com2
			return "success"; // com3
		default:
			System.out.println("wrong number!");
			return "failue";
		}
This is a good example on how the design of Comments class makes comments management much easier (in my opinion).

**Comment by OriRoth** [comment]
Added a new wring SwitchFewCasesReplaceWithIf to replace small switch statements (1 case maybe with default) with an if statement. Not only there is comments preservation, but also I have added some new mechanics to Comments class in order to place them in the original place in the code (as much as possible). Use example:
<pre><code>
void g(int i) {
	switch (i) {
	case 1: /\*case 1\*/
		System.out.println("1 detected!");
		break;
	default:
		System.out.println("error!"); // fatal error
		break;
	}
}
</pre></code>
==> (notice line comment at original place - important for large chunks of code)
<pre><code>
void g(int i) {
	/\*case 1\*/
	if (i == 1) {
		System.out.println("1 detected!");
	} else {
		System.out.println("error!"); // fatal error
	}
}
</pre></code>
==>
<pre><code>
	void g(int i) {
		/\*case 1\*/
		// fatal error
		System.out.println(i != 1 ? "error!" : "1 detected!");
	}
</pre></code>

**Comment by OriRoth** [comment]
Added a new wring SwitchSimplify to remove unnecessary cases from a switch statement:
<pre><code>
switch (x) {
case 1: // unused
case 2:
  System.out.println("2 detected!"); // used
default:
  break;
}
</pre></code>
==>
<pre><code>
// unused
switch (x) {
case 2:
	System.out.println("2 detected!"); // used
}
</pre></code>
No tests were built for the switch's wrings yet! see issue #35.

**Comment by OriRoth** [comment]
Added a new wring IfToSwitch to replace if statement with switch statement, when it make sense. Again, this wring must be tested soon!
If statement becomes switch only when it is:
a) possible
b) the switch statement would have at least 3 cases (including default, changeable)
<pre><code>
if ("1".equals(s))
	System.out.println(s);
else if ("2".equals(s))
	System.out.println(s + "!");
else {
	s += "@"; // @ is good here
	System.out.println(s);
}
return 0;
</pre></code>
==>
<pre><code>
switch (s) {
case "1":
	System.out.println(s);
	break;
case "2":
	System.out.println(s + "!");
	break;
default:
	s += "@"; // @ is good here
	System.out.println(s);
	break;
}
return 0;
</pre></code>
==>
<pre><code>
switch (s) {
case "1":
	System.out.println(s);
	return 0;
case "2":
	System.out.println(s + "!");
	return 0;
default:
	s += "@"; // @ is good here
	System.out.println(s);
	return 0;
}
</pre></code>

**Comment by yossigil** [comment]
The ideal speartanization of a switch will do the following:

1.  Analyse the code of each branch. A branch. is either a case ".." : or default:
2. Attach to each branch, the code that it executes.
For example, for the input:
```
switch (a) {
   case 1:
     f();
  case 2:
    g();
    return 1;
   case 3:
     f();
  case 4:
    g();
    break;
  case 5:
    f();
   g();
case 6:
   break;
 case 7:
    f(); 
 case 8:
    g();  
    break;
 default:
  h();
  case 9:
   return 1;
 default: 
   f();
  case 10:
   g();
}`
```

The output would contain: 
- 1: f(); g(); return 1; 
- 2: g(); return 1; 
- 3:: f(); g(); break;
- 4: g(); break;
- 5: f(); g(); break;
- 6: break;
- 7: f(); g(); break;
- 8: g(); break;
- 9: return 1;
- default: f(); g(); break;
- 10: g(); break;

The next step would be to consolidate entries


- 1: f(); g(); return 1; 
- 2: g(); return 1; 


- 6: break;



- 4,8: g(); break;

- 3,5:: f(); g(); break;
- 9: return 1;



- 7: f(); g(); break;


- default: f(); g(); break;
- 10: g(); break;

**Comment by OriRoth** [comment]
See wring SwitchDeductStatementsForCase. This wring makes sure each case within a SwitchStatement would end with a sequencer, using branch analysis. Use Example:
<pre><code>
switch(x/\*x\*/) {
case /\*1\*/1:
	System.out.println("!");
case 2: // 2
	System.out.println("?");
	return 2;
default:
	System.out.println("d");
case 3:
	System.out.println("#");
	// 3
}
</pre></code>
==>
<pre><code>
switch (x/\*x\*/) {
case /\*1\*/1:
	System.out.println("!");
	System.out.println("?");
	return 2;
case 2: // 2
	System.out.println("?");
	return 2;
default:
	System.out.println("d");
	System.out.println("#");
	// 3
	break;
case 3:
	System.out.println("#");
	// 3
	break;
}
</pre></code>

**Comment by OriRoth** [comment]
Deprecated SwitchDeductStatementsForCase, updated SimplifySwitch to deal with the above issue. Use example:
```
switch (x) {
case 1:
	System.out.println("1"); // com1
case 2:
	break;
case 3:
	System.out.println("1"); // com2
	break;
case 4:
	break;
case 5:
	System.out.println("!");
	throw new Exception();
case 6:
	throw new Exception(); // oops
default:
	throw new Exception();
}
```
==>
```
// com2
// oops
switch (x) {
case 5:
	System.out.println("!");
	throw new Exception();
case 1:
case 3:
	System.out.println("1"); // com1
	break;
case 2:
case 4:
	break;
default:
	throw new Exception();
}
```
remark: **NOT TESTED YET**
@yossigil should we add cases expression sorting (as in ternary shortest first)? what about removing cases with body = break statement (when there is no default)?
