### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#39]
See this image: 
![screenshot from 2016-06-01 21-49-06](https://cloud.githubusercontent.com/assets/12775400/15721746/064fc334-2843-11e6-9b11-40ea862e6997.png)

**Comment by OriRoth** [comment]
I also get errors when debugging the project. Daniel said there have always been errors during the launching. How did you get this log? by running the debugger?
![crash](https://cloud.githubusercontent.com/assets/15183108/15747321/dfc89484-28e2-11e6-9298-278bf8d8cc5f.jpg)

**Comment by yossigil** [comment]
We no longer support old versions. reopen if persists in Neon
