### ISSUE TITLE
Document class Subject

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#51]
This fluent API class may be tough to understand, but it should be easy to use. document it.

**Comment by dormaayan** [comment]
I want to use the @see anotation in my documentation, 
do you have any idea how do I get the links to the methods ?
I tried the package name and then # but it doesn't work...

**Comment by dormaayan** [comment]
I documented it
@yossigil please look and if it seems ok you can close that issue.

**Comment by yossigil** [comment]
It looks fine. The main point is that you should understand how it works. I applied minimal polishing. take a look. Fixed the @see as well (I think)

**Comment by yossigil** [comment]
Dor: take a look; some more polishing
