### ISSUE TITLE
Write unit tests for RedundantModifiers

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#52]
There are few, but we need more. Some of them should show that we remove the right modifiers. The others should show that we do not remove modifiers which cannot be removed. Write all these in TrimmerTest

**Comment by dormaayan** [comment]
Does the RedundantModifiers can currently recognize redundancy of modifiers in a declaration of a field in an interface ?
For example, when I try to trim 
public interface Int1 {
        public int num = 5;
        }
I get exactly  the same code

**Comment by dormaayan** [comment]
Also, it doe't look like it works on nested enums (for example, when I declare one of the nested enums as static)
The rest of the cases except does two above seems to work fine

**Comment by yossigil** [comment]
Good job Dor! The first was a bug regarding dispatching; the second? look at function named issue52p(); trimming does only one thing at a time, so you had to do one more iteration.

All: please examine all functions named issue52p()
