### ISSUE TITLE
Build fails in Eclipse Mars 2 with Project Lombok annotations

### ISSUE THREAD

**Issue by mmeany** [SpartanRefactoring/spartan-refactoring#7]
I am using Eclipse Mars 2 and have Lombok installed as a java agent. I installed Spartan Refactoring from the Eclipse Marketplace.

The project I am working on is a Maven multi-module.

On starting Eclipse the following error is displayed:

```
Errors occurred during the build.
Errors running builder 'Spartanization Checker' on project 'camel-microservices'.
Invalid string literal : >@Data<
Errors running builder 'Spartanization Checker' on project 'first-steps'.
Invalid string literal : >@Data<
```

As I use Lombok just about everywhere I had to uninstall the plugin

**Comment by mittelman** [comment]
Hi, thanks for the report.
I've been able to reproduce the error message you've received, I'll check and see where the problem is.

**Comment by yossigil** [comment]
sakopzon
