### ISSUE TITLE
Remove unary plus

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#75]
As in +0, +x, etc.

**Comment by yossigil** [comment]
@M4tt30rru : should be easy

**Comment by M4tt30rru** [comment]
Does it applies to assignments like the following?

int a = +1;
int b = +0;
int c = +b;

**Comment by yossigil** [comment]
Of course. Just hook on the PostfixExpression, and NumberLiteral and this should do it all.

**Comment by yossigil** [comment]
Is this done? If so, please close.
