### ISSUE TITLE
Check launcher

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#80]
@sakopzon

**Comment by mittelman** [comment]
It seems that the plugin loads just fine, however there's a problem with one of the handlers. I'm testing this on Eclipse Neon, so this may be because there have been changes with the Eclipse SDK.

Looking into the issue

**Comment by mittelman** [comment]
It seemed that there were some erroneous values in the builder and the nature's classes. After fixing them, I was successful at running the plugin on Eclipse Neon from the "Plugin" run configuration.

Closed for now.
