### ISSUE TITLE
Complete work on CollectionSize wring

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#83]
I think I never finished it.

**Comment by yossigil** [comment]
@NivShalmon , @dormaayan , @Stav1472  this is for you guys.
@dormaayan shall summarize in a comment below our discussion today, test cases, write tests
before implementation, poor man's heuristic to deal with the case of no binding information, etc.

**Comment by dormaayan** [comment]
In a situation we don't have any binding information we want to deal with the following cases : 
`if(lst.size>=0)` --> `if(true)`
`if(lst.size<0)` --> `if(false)`
`if(lst.size == 0)` --> `if(lst.isEmpty())`
`if(lst.size == 1)` --> `if(!lst.isEmpty())`
`if(lst.size == 2)` --> `if(!lst.isEmpty())`

- Cover those cases in `Replacement`
- Implement it in the most elegant way as possible.
- There are already some tests (marked as @ignore) that suppose to cover at least some of the cases, we need to add more tests.

**Comment by dormaayan** [comment]
@yossigil  :
We worked on that today,
It now passes all the tests we added in trimmer.
But, we don't yet handle with the case we need to change it to true and false, as we asked you on telegram.
Moreover, we aren't sure how do you want us to combine the cases where we have binding and where we don't have, can you look at the code ?

**Comment by dormaayan** [comment]
@yossigil  :
Got the issue with the true/false, now also pass those tests
now you can look at the code and close the issue if you think we are done and we don't need to separate the cases of Binding and no-Binding

**Comment by NivShalmon** [comment]
@yossigil 
I've organised the wring a bit and changed it so it would handle comparison to negative numbers as well. I've also added tests for comparison to negative numbers.
The wring is complete, aside for one final issue:
Should we use binding to check whether isEmpty() exists or not in the scope, when it is possible? It could prevent change to code that doesn't compile in the odd situation where size() exists but isEmpty() doesn't, but it appears we can't test this right now.
If tou don't want us to use binding when avialable, than this issue can be closed.

**Comment by yossigil** [comment]
Yes, do try to use binding when present. Currently, the test don't do that, so you would have to use mockito 
(eventually)

**Comment by yossigil** [comment]
@NivShalmon : if the binding code is there, even thought untested, then we are good; close this issue

**Comment by NivShalmon** [comment]
Readded the binding check that exsited in the original version of the wring, and adjusted it to run only if binding is available. It is currently untested
