### ISSUE TITLE
[if (true) s;] => [S]:  "No Impact" wring

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#85]
Should not be in "real" code.

Dor: I see that you are catching with stuff. Can you do this one using class Subject that you documented,.
Feel free to share with @Phantom1472  and @NivShalmon

**Comment by dormaayan** [comment]
@yossigil  :
I wrote a new wring that I think should be work, but when I wrote a simple test (I added it in trimmerTest) and put a breakpoint in the function replacement (that I implemented) it isn't even reach there, and the test fails.
Are there places where i should add my new wring to in order that it will be recognized ?

**Comment by yossigil** [comment]
The spartanization engine has to know about your new wring. Just writing a class does not make the engine know about it. You have to do two things: 

1. add an instance of the class to Toolbox.
2. Make sure that Trimmer dispatches correctly based on the type of this class. This is already true for If classes, as you would need here, but not necessarily for other types. Most important types are there already though.

**Comment by dormaayan** [comment]
@sakopzon :
Next time, when you decide to work on a subject your are not assigned to, please let us know, that will prevent some people to work on the same issue...
