### ISSUE TITLE
Wiki: add a page explaining what to do before push

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#88]
Stages should include:
a. Formatting of all code. Explain how to use our formatter
b. Organizing imports.
c. Cleanup: explain how to use our cleanup configuration
d. Member sorting of large classes.
e. Running tests.

**Comment by yossigil** [comment]
Also, include tips such as:

- Always pull before you start working
- Refresh project in eclipse.
- Fix the project setup/buildpath

**Comment by yossigil** [comment]
Please update for our meeting today

**Comment by sakopzon** [comment]
what do you mean under organizing imports? (other then alphabetically?)

**Comment by yossigil** [comment]
I could not find the page, can you please add a link to it here?

**Comment by dngreenst** [comment]
https://github.com/SpartanRefactoring/spartan-refactoring/wiki/Spartan-Git-How-To

**Comment by yossigil** [comment]
Thanks
