### ISSUE TITLE
Build fails in Eclipse Indigo Service Release 2

### ISSUE THREAD

**Issue by Mikalovicz** [SpartanRefactoring/spartan-refactoring#9]
On starting Eclipse the following error is displayed:
![13ae74766af66b29](https://cloud.githubusercontent.com/assets/5630933/14001692/2410fb44-f126-11e5-921a-0187a3baedda.jpg)

**Comment by mittelman** [comment]
Probably the same issue as issue #7

**Comment by yossigil** [comment]
@OriRoth  can you please look into it?

**Comment by yossigil** [comment]
We only support Neon
