### ISSUE TITLE
Wrings for Arithmetic: 1.+2*3 / 4 - 5 goes, eventually, to -3.,

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#92]
Don't change expressions that  involves anything other than  literals, i.e., don't touch ` a + 2`, nor `"0" + 1` but other than that you can go wildly, as long as you manage type information:

1. int
2. long
3. double
4. short (not sure is necessary).

And climb up as you may need. The climbing up may a bit complex, say, what happens if you multiply a short by a long, etc. 

Please search the Java language specification for this, I believe this is this [chapter](https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.1)

Now, the main programming/OOP challenge here is dispatching on the operator type, that is, when you see a `+` you invoke a `plus()` function, and when you see a `<< ` you invoke function `rightShift()`. Top managing type information, and you have a great [OOP exercise.](https://docs.google.com/document/d/1esA2tYcRQVC2ZqPD4WfWS0PKlHJqJS8Tudeh1yEHkI0/edit?usp=sharing) 

I suggest considering table driven programming for the task of dispatch. You could have done a hierarchy that represent the type of literals in arithmetic , and another for the kinds of operations, but it may be possible to do achieve the same effect, by having a table to say something of the sort of
`int @opcode int -> int` and 
`long @opcode long -> long` entries in it.

Start with writing the test case, create a copy of `TestTrimmer250` and name it `ArithmeticTest`.  Clear all unit tests (i.e,, `@Test` methods)  in your newly created and empty `ArithmeticTest` test suite. To do so, take a quick look at the fluent test examples you in `TestTrimmer250`. You should get the hang of it pretty easily.

Feel free to commit code with `@Test`s that fail. Just make sure you prefix these with  `@Test`s with something like `@Ignore("#1472:under construction")` , where `1472` is whatever this issue number turns to be.  Your tests should look like [this](https://gist.github.com/yossigil/b0914a919427facf905e7041d37c41b5)

https://gist.github.com/yossigil/b0914a919427facf905e7041d37c41b5

So, let me know, you may be interested, but it might be too detailed or boring.

`

- A long number literal is not a literal
- A double number literal is not a literal

**Comment by yossigil** [comment]
I will let @dormaayan  finish it.

**Comment by yossigil** [comment]
You may need to use something out of #94 done by @NivShalmon

**Comment by dormaayan** [comment]
@yossigil :

- Im not sure what is the right approach to that mission, Do you suggest to divide the tasks to many small wrings and to start with the simple cases (each wring does a simple operations over numbers of the same type) or to do everything in one big wring ?

- What do you mean by managing the types ? Do I need to relay on the work of @NivShalmon ?

- Should I also consider "(",")" order in my evaluation ?

**Comment by yossigil** [comment]
This is not an import wring. We could do without it. but, it makes a good example:

- Yes, it is wise to do small steps. The idea is to get into an an expert system, which could apply wrings in different order: #93 
- No, you do not have to rely on it, certainly not in the first round.  But, you will find yourself doing something similar. You need to know that integers promote to long that promote to double.
- Not really a question, you compute in the order of the tree. Should be easy, but make sure to use `extract` to find out all operands of an infix such as + in the expression `12+3+4.0-1L` (operator + has three arguments: left, right, and extraOperands which `extract` can give  you as plain list of size at least two.

**Comment by dormaayan** [comment]
@yossigil  :
Now, I added a wring that evaluate addition of integers and it is actually work so good that many other tests don't pass now because the first thing happens is the evaluation...
Do you want me to change all the those tests or to do something else ?
(I  also noticed that if I declare my new wring in toolbox.java after  new InfixAdditionSort() nothing happens , do you have any idea why ?)

**Comment by yossigil** [comment]
If it is just a matter of another test getting confused, fix it. Other wise come speak to me.

**Comment by dormaayan** [comment]
@yossigil  :  why did you close that issue ? I'm not done yet...
Can you please reopen it ?

**Comment by yossigil** [comment]
I just reopened it. Sorry. Keep on testing this one. It is fairly tricky.
Here is an example you should try:

Create simple classes with one or two at most three instance variables, of various primitive types: int, long, double, char, short, byte (boolean? not sure) 
Then make Eclipse generate equality and hash functions. See how much you can simplify them.
after doing it live, go and make test case out of it with long trimming to to to to to ... chain

**Comment by dormaayan** [comment]
I handled with : `+,-,*,/,%,>>,<<` for `int,double,long` and tested it, it seems to be working fine
@yossigil : I think we can close that issue
