### ISSUE TITLE
PrudentType what a rational prudent programmer will guess

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#94]
@NivShalmon  this is for you. Fill in test cases to make the type inference work.
You should start with class Kind  and then proceed to fill up the tests and the implementation of
of function kind();

- [x] See if you can rename Kind to Type. Might be tricky.

**Comment by NivShalmon** [comment]
I don't quite understand what I'm supposed to do.
I tried to search for a Type class, but I couldn't find any Type class or interface within our code (only in jdt's and other outside code). I did find two classes named Kind, an interface in il.org.spartan.refactoring.wring and an enum in Type.java that's in il.org.spartan.refactoring.utils of the tests. Which one am I supposed to rename and work on?

**Comment by yossigil** [comment]
Look for this class:

```
package il.org.spartan.refactoring.utils;

import static il.org.spartan.Utils.*;
import static il.org.spartan.refactoring.utils.Funcs.*;
import static org.eclipse.jdt.core.dom.PrefixExpression.Operator.*;

import javax.management.*;

import static org.eclipse.jdt.core.dom.InfixExpression.Operator.*;

import org.eclipse.jdt.core.dom.*;
import org.omg.CORBA.*;

/** TODO: Niv Issue*94
 * 
 * <p>Tells how much we know about the type of of a variable, function, or
 * expression.
 * <p>
 * Dispatching in this class should emulate the type inference of Java. It is
 * simple to that by hard coding constants.
 * <p>
 * This type should never be <code><b>null</b></code>. Don't bother to check
 * that it is. We want a {@link NullPointerException} thrown if this is the
 * case. or, you may as well write
 * 
 * <pre>
 * Kind k = f();
 * assert k != null : //
 * "Implementation of Kind is buggy";
 * </pre>
 * 
 * @author Yossi Gil
 * @since 2016-08-XX */
enum Kind {
  // Those anonymous characters that known little or nothing about themselves
  NOTHING("none", "when nothing can be said, e.g., f(f(),f(f(f()),f()))"), //
  NONNULL("!null", "e.g., new Object() and that's about it"), //
  BAPTIZED("!double&!long&!int", "an object of some type, for which we have a name only"), //
  VOID("void", "nothing at all"),
  // Doubtful types, from four fold uncertainety down to bilalteral
  // schinography" .
  ALPHANUMERIC("String|double|long|int|", "only in binary plus: f()+g(), not 2 + f(), nor f() + null"), //
  NUMERIC("double|long|int", "must be either f()*g(), 2L*f(), 2.*a(), not 2 %a(), nor 2"), //
  INTEGRAL("long|int", "must be either int or long: f()%g()^h()<<f()|g()&h(), not 2+(long)f() "), //
  // Certain types
  NULL("null", "when it is certain to be null: null, (null), ((null)), etc. but nothing else"), //
  INT("int", "must to be int: 2, 2*(int)f(), 2%(int)f(), no 2*f()"), //
  LONG("long", "must be long: 2L, 2*(long)f(), 2%(long)f(), no 2*f()"), //
  DOUBLE("double", "must be double: 2.0, 2.0*a()+g(), no 2%a(), yes 2*f()"), //
  BOOLEAN("boolean", "must be boolean: !f(), f() || g() "), //
  STRING("String", "must be string: \"\"+a, a.toString(), f()+null, not f()+g()"),//
  ;
  final String description;
  final String name;

  Kind(final String name, final String description) {
    this.name = name;
    this.description = description;
  }

  public final String fullName() {
    return this + "=" + name + " (" + description + ")";
  }

  public final Kind under(final PrefixExpression.Operator o) {
    assert o != null;
    assert in(o, BOOLEAN, MINUS1, PLUS1, COMPLEMENT, DECREMENT_POST, DECREMENT_PRE);
    return o == NOT ? BOOLEAN //
        : in(o, MINUS1, PLUS1) ? asNumeric() //
            : underIntegersOnlyOperator();
  }

  /** @return one of {@link #INT}, {@link #LONG}, or {@link #INTEGRAL}, in case
   *         it cannot decide */
  public Kind underIntegersOnlyOperator() {
    return in(this, LONG, INT) ? this : INTEGRAL;
  }

  /** @return one of {@link #INT}, {@link #LONG}, {@link #DOUBLE},
   *         {@link #INTEGRAL} or {@link #NUMERIC}, in case no further
   *         information is available */
  public Kind asNumeric() {
    return in(this, DOUBLE, LONG, INT, INTEGRAL) ? this : NUMERIC;
  }

  /** @return one of {@link #INT}, {@link #LONG}, {@link #DOUBLE},
   *         {@link #STRING} or {@link #ALPHANUMERIC}, in case it cannot
   *         decide */
  public Kind underPlus(Kind k) {
    return k == STRING && this == STRING ? STRING : ALPHANUMERIC;
  }

  /** @return one of {@link #INT}, {@link #LONG}, {@link #DOUBLE}, or
   *         {@link #NUMERIC}, in case it cannot decide */
  private Kind asNumeric(Kind k) {
    if (k == this)
      return k;
    if (!isNumeric())
      return asNumeric().asNumeric(k);
    assert (k != null);
    assert this != ALPHANUMERIC : "Don't confuse " + NUMERIC + " with " + ALPHANUMERIC;
    assert in(this, INT, DOUBLE, LONG, INTEGRAL, NUMERIC) : this + ": does not fit our list of numeric types";
    assert isNumeric() : this + ": is for some reason not numeric ";
    final Kind $ = k.asNumeric();
    assert $ != null;
    assert $.isNumeric() : this + ": is for some reason not numeric ";
    assert in($, INT, DOUBLE, LONG, INTEGRAL, NUMERIC) : $ + ": does not fit our list of numeric types";
    if ($ == this)
      return $;
    if (in(DOUBLE, $, this))
      return DOUBLE;
    assert in($, INT, LONG, INTEGRAL, NUMERIC) : $ + ": does not fit our narrowed list";
    assert in(this, INT, LONG, INTEGRAL, NUMERIC) : this + ": does not fit our narrowed list";
    if (in(NUMERIC, $, this))
      return NUMERIC;
    assert in($, INT, LONG, INTEGRAL) : $ + ": does not fit our narrowed list";
    assert in(this, INT, LONG, INTEGRAL) : this + ": does not fit our narrowed list";
    // Numeric contaminates INTEGRAL
    if (in(INTEGRAL, $, this))
      return INTEGRAL;
    assert in($, INT, LONG) : $ + ": does not fit our narrowed list";
    assert in(this, INT, LONG) : this + ": does not fit our narrowed list";
    // LONG contaminates INTEGRAL
    if (in(LONG, $, this))
      return LONG;
    assert in($, INT) : $ + ": does not fit our narrowed list";
    assert in(this, INT) : this + ": does not fit our narrowed list";
    return INT;
  }

  private boolean isNumeric() {
    return in(this, INT, LONG, DOUBLE, INTEGRAL, NUMERIC);
  }

  private Kind underIntegersOnlyOperator(Kind k) {
    final Kind ¢ = k.underIntegersOnlyOperator();
    return !in(¢, this, INTEGRAL) ? max(¢) : ¢ != Kind.ALPHANUMERIC ? ¢ : INTEGRAL;
  }

  private Kind max(Kind ¢) {
    return ¢.ordinal() > ordinal() ? ¢ : this;
  }

  public final Kind underBinaryOperator(InfixExpression.Operator o, Kind k) {
    if (o == PLUS2)
      return underPlus(k);
    if (in(this, //
        LESS, //
        GREATER, //
        LESS_EQUALS, //
        GREATER_EQUALS, //
        EQUALS, //
        NOT_EQUALS, //
        CONDITIONAL_OR, //
        CONDITIONAL_AND//
    ))
      return BOOLEAN;
    if (in(o, REMAINDER, LEFT_SHIFT, RIGHT_SHIFT_SIGNED, RIGHT_SHIFT_UNSIGNED, XOR, OR, AND))
      return underIntegersOnlyOperator(k);
    if (!in(this, TIMES, DIVIDE, MINUS2))
      throw new IllegalArgumentException("o=" + o + " k=" + k.fullName() + "this=" + this);
    return asNumeric(k);
  }

  public static boolean kind(Expression e) {
    throw new RuntimeException("Team3 needs to implement this: " + e);
  }
}
```

**Comment by NivShalmon** [comment]
@yossigil I updated some basic tests for currently implemented methods, but they don't pass them right now, so I want to make sure I understood them currectly. From what I understood, the goal of the under methods is to use the types and operands to return the most specific type information about the result of the operation. If I understood currectly than I can start working on these methods right away.
Also, some of the access modifiers seem inconcictent here, for example asNumeric() is public while asNumeric(Type) is private, and underIntegersOnlyOperator(Type) is the only private under method.

**Comment by yossigil** [comment]
Make sure it covers everything! Use this [tool](http://www.eclemma.org/)

**Comment by yossigil** [comment]
Yes. The methods are designed so as to give you the most accurate type information for each expression. 
Read the string and comments: if something is of type, then it has been proved to be of type an no other type. 

Try to make methods as private as possible.

**Comment by NivShalmon** [comment]
@yossigil I thought of the following idea while debating the access modifiers for methods and how to implement kind(), and would like to hear your idea:
I'm planning to implement kind reccursively. We may sometimes know some of the operand's Type in advance (if I understand correctly, Environment.Information would achive something to this extent once implemented) and than we won't want to use the recursive kind. I thought to create two more versions of kind that accept one or two Types of operands (for single opperand and 2 opperands expressions) that would allow to re-use kind's code for this case, and than any other method in the class can be private, without hurting our abillity to reuse this code.
What do you think?

**Comment by NivShalmon** [comment]
@yossigil I just noticed kind's return value is boolean, rather than Type, so either it's a mistake or I don't know what kind is supposed to do. Can you clarifiy?

**Comment by NivShalmon** [comment]
Also, I think that the enum should also include CHAR. It can appear in any place any other INTEGRAL can and is more specific than INT is. Should I add it?

**Comment by NivShalmon** [comment]
A basic version of kind is now avaliable. It can handle the following cases:

- literals (except type literals)
- casting
- all prefix and infix expressions
- parenthesis

Things I still need to do:

- [ ] Constructors
- [ ] toString() calls
- [ ] everything related to arrays
- [ ] postfix expressions - should these even be handled? We have wrings that change them to prefix operators without depending on Kind.
- [ ] expressions such as ConditionalExpression with no real Type. These should probably return VOID.

@dormaayan The current version should work with arithmetic expressions, you should be able to use it in issue #92.

**Comment by yossigil** [comment]
Comment:

1. Constructors should be easy. They just return non-null
2. To string returns String.
3. You are right, arrays are a nuisance
4. Yes, we should do postfix. Postfix is always int/log/Integral. It adds information.
5. Conditionals should give the most common type. Ig. f() ? X : Y is
long if X is long and Y is int. It is is Alphanumerc otther wise.
 They are not void.
6. Interface to class should be something like:
Kind k = KInd.tell(ASTNode) {

}
while the function tell should give the best available kind information.

**Comment by NivShalmon** [comment]
In `f() ? X : Y` if X is long and Y is int, shouldn't it be INTEGRAL rather than long, since the type is undetermined? Saying it is long is unaccurate, and might cause wrong conversions when used by wrings.
Also, consturctors sometimes return more specific information, for example new int(7) returns an INT, rather than a general NONNULL. Currently the code takes those cases into consideration, and returns the specific type the constructor creates.
Finally, about the CHAR type. While there is no diffrence between INT and CHAR to the code of kind, I belive the user may sometimes want to tell INT and CHAR appart (for exmaple in issue #92), so for now I will leave that in there.

**Comment by yossigil** [comment]
Clever thought, but I am not sure you are right. Consider the case of a function call `g(f() ? X : Y)` and then suppose that `g` has two overloaded versions, one with `int` argument and another with a `long` argument. What do you think will happen? My bet is that the result is of type `long`, but who knows. I never checked.

**Comment by NivShalmon** [comment]
I tested it a bit on a few cases both function calls and arithmetic expressions and it appears the type of the conditional realy is `long`, even in obvious cases such as `true ? 1 : 1L`.

**Comment by yossigil** [comment]
yes I guessed as much.
now make sure you've a test case for thus case and then go ahead and implement it

**Comment by yossigil** [comment]
@ dormaayan also fyi

I changed the name of this class to RationalType

**Comment by yossigil** [comment]
two more points you raise are
.handling of extra information. it is tough especially ity array literals and the such 

good if you did but this is nor so important 
don't start it now. 

the low hanging fruit are in type analysis. this would have to wait

**Comment by NivShalmon** [comment]
PrudentType isn't quite done, but it is ready for use in most cases. I think this should be enough for now, at least until I'm done with issue #101.
@yossigil anything you think I should add before moving on? I think that other than arrays, I'm missing mostly cases that should return VOID rather than NOTHING

**Comment by yossigil** [comment]
Please integrate with

- [ ] LiteralParser.Type. Just use some of the types from the PrudentType,.
- [ ] stringType which includes a heuristic for determining if anything is a string.

The last one is a bit more difficult, since it may require you to go both up and down in the analysis. I cannot quite reconstruct this but I think there are cases you can infer that something must be  a string, based on how it is used.

**Comment by NivShalmon** [comment]
@yossigil 
About LiteralParset.Type, should I simply change it to return PrudentType rather than int?
And about stringType, I belive PrudentType can replace both notStringSelf and isNotFromStructure and impore accuracy of this. Do you also want me to try and improve isNotFromContext as well?

**Comment by yossigil** [comment]
Yes. You can do so. 
Yes, it would be good. Clever work. Thanks.

**Comment by yossigil** [comment]
I think you need to introduce type "boolean|integral".

**Comment by NivShalmon** [comment]
After trying to integrate PrudentType into stringLiteral, I found out a pretty big mistake regarding infix plus.
Unless we know all operands are `NUMERIC`, the result of a plus is either `ALPHANUMERIC` or `STRING`. That is because a single `STRING` or `NULL` will make the result a `STRING` , regardless of the other operands.
After fixing this bug, stringType now uses PrudentType for the context check. I still need to see if I can integrate it into the context check.

The change to stringType did cause one odd case though, in TrimmetTest250.issue70_11:
(double)f + (int)g is first sorted, than (double)f is changed to 1.*f and than sorted again. I changed the test to fit this order, but optimally we sould not sort this at all.

**Comment by NivShalmon** [comment]
It seems to me that PrudentType can't be used for the context check in any way, so I'm done integrating it within stringType.
@yossigil I don't think there is much left to do in this issue, but currently VOID is never returned. Do you have an example for an expression whose type is VOID?

**Comment by yossigil** [comment]
No, I do not have an example for void. Let's close this one.
There is more work to do on this one, regarding inward inference, e.g.,
`if (a&b)` tells you that a and b are integral types, whereas up analysis would tell you that 
they are either boolean or  integral. Same for '(a+b)*c'. If you just analyze a+b, you know that they are either strings or numeric. But when you see *c, you know that they must be numeric.
