### ISSUE TITLE
Spartanize entire project

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#97]
- [x] Apply the plugin on itself.

- [ ] Apply the market version.

- [x]  Prepare test cases for the cases in our code in which either one fails. The containing class may be @Ignored.

**Comment by Stav1472** [comment]
Let me make sure that I understand the issue correctly:
you want me to spartanize the more-stable branch with the more-stable branch code, then spartanize the more-stable branch with the master's code and from the compilation errors each one gives prepare tests? should I push the spartanized code? 

also, what do you mean by "the containing class can be @Ignored"?

**Comment by yossigil** [comment]
Brilliant.Push the spartanized code, after making sure it is correct.

Make a new test class
```
@Ignore("Issue("*97": under construction")//
 public class TestSwitch {
@Test public void test01() {
trimming("from").to("to").to(null);
}
}

**Comment by Stav1472** [comment]
Ok, i think i understand what you want, but how should i know what the spartanized code would look like? it's not so simple to figure out sometimes...

also, you want the tests of master to be pushed to master, and the tests of more-stable to be pushed to more-stable, right? (just verifying)

**Comment by yossigil** [comment]
Do your best. The tests are @Ignored' so don't worry too much. Please start getting some work done.

**Comment by Stav1472** [comment]
Ok. thanks!

**Comment by yossigil** [comment]
There are 55 spartanization  infos now.

**Comment by Stav1472** [comment]
i seem to not get spartanization infos for some reason. also, i have canceled a few of them because of compilation error or wrong transformations.

**Comment by Stav1472** [comment]
well, I've gone over the whole project with the master branch. nothing to spartanize. can you show something you get an info about?

**Comment by yossigil** [comment]
![image](https://cloud.githubusercontent.com/assets/12775400/18034264/54a52f68-6d41-11e6-9cee-8a760b1a31b8.png)

סתו, אני ממש לא מבין
אם אתה חומד לך לצון, אז זה לא מצחיק.

מצ"ב תמונה של 65  הודעות.

**Comment by Stav1472** [comment]
Done spartanizing for the new master, old master has tests errors and failures, so i can't use it.
tests for master are done.

**Comment by yossigil** [comment]
OK. I took over this one and did it. It did not look as if you are going anywhere, the number of warnings doubled.
