### ISSUE TITLE
GIT BRANCH REARRANGEMENT

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#98]
- [x] Freeze all activity. Lock if possible.
- [x] Create a new branch `old-master-2016-`MM-DD where MM-DD are e.g., `08-27`for the 27th of August.
- [x] Move branch `master` to  `old-master-2016-MM-DD`
- [x] Everything that is in `more-stable` goes to `master` now
- [x] Vaporize branch `more-stable` 
- [x] Melt all activity. Unlock if necessary.

**Comment by mittelman** [comment]
Done!
